# Lambda function

In [ ]:
x = lambda a : a + 10

print(x(5))

In [ ]:
x = lambda a, b : a * b
print(x(6, 7))

In [ ]:
def myfunc(n):
  return lambda a : a * n

mydoubler = myfunc(2)

mydoubler(13)

## Numpy code along


In [1]:
# 'np' is the conventional alias for numpy
import numpy as np

#### Numpy arrays

In [2]:
## one dimensional array is a vector
a = np.array([5,3,2])

In [3]:
a

array([5, 3, 2])

#### Generate an array with random numbers

In [13]:
np.random.seed(1000)
a = np.random.random((6,3))
a

array([[0.65358959, 0.11500694, 0.95028286],
       [0.4821914 , 0.87247454, 0.21233268],
       [0.04070962, 0.39719446, 0.2331322 ],
       [0.84174072, 0.20708234, 0.74246953],
       [0.39215413, 0.18225652, 0.74353941],
       [0.06958208, 0.8853372 , 0.9526444 ]])

### Other ways to create arrays

#### List to array

This works the same way whether you have a list of lists, a list of tuples, a tuple of lists, or a tuple of tuples.

In [16]:
lst_lst = [[1,2,3],[4,5,6],[7,8,9]]
d = np.array(lst_lst)
print(d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


#### Constant arrays

In [17]:
a = np.zeros((2,2))  # Create an array of all zeros
print(a, "\n")

b = np.ones((3,2))   # Create an array of all ones
print(b, "\n")

c = np.full((2,2), 7) # Create a constant array
print(c)

[[0. 0.]
 [0. 0.]] 

[[1. 1.]
 [1. 1.]
 [1. 1.]] 

[[7 7]
 [7 7]]


#### Sequential arrays

In [18]:
# Create an array filled with a linear sequence
# Starting at 0, ending at 20, stepping by 2
# (this is similar to the built-in range() function)
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [19]:
# Create an array of five values evenly spaced between 0 and 1
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [20]:
# Create a 3x3 array of normally distributed random values
# with mean 0 and standard deviation 1
np.random.normal(0, 1, (3, 3))

array([[-0.13842199,  0.70569237,  1.27179528],
       [-0.98674733, -0.33483545, -0.0994817 ],
       [ 0.4071921 ,  0.91938754,  0.31211801]])

In [21]:
# Create a 3x3 array of random integers in the interval [0, 10)
np.random.randint(0, 10, (3, 3))

array([[1, 0, 2],
       [1, 7, 1],
       [5, 6, 5]])

#### Array Attributes

In [22]:
np.random.seed(123)
a = np.random.random((6,3))
a

array([[0.69646919, 0.28613933, 0.22685145],
       [0.55131477, 0.71946897, 0.42310646],
       [0.9807642 , 0.68482974, 0.4809319 ],
       [0.39211752, 0.34317802, 0.72904971],
       [0.43857224, 0.0596779 , 0.39804426],
       [0.73799541, 0.18249173, 0.17545176]])

In [23]:
a.shape

(6, 3)

In [24]:
a.size

18

In [25]:
a.ndim

2

In [26]:
a.dtype

dtype('float64')

In [30]:
b = np.array([1,3,4])

In [31]:
b.dtype

dtype('int64')

In [32]:
b.itemsize

8

In [ ]:
c = np.array([1,3,4], dtype="int8") # smaller integers
#np.astype(int64)

In [33]:
c.itemsize

8

#### Array indexing

In [34]:
a

array([[0.69646919, 0.28613933, 0.22685145],
       [0.55131477, 0.71946897, 0.42310646],
       [0.9807642 , 0.68482974, 0.4809319 ],
       [0.39211752, 0.34317802, 0.72904971],
       [0.43857224, 0.0596779 , 0.39804426],
       [0.73799541, 0.18249173, 0.17545176]])

In [35]:
a[0]

array([0.69646919, 0.28613933, 0.22685145])

In [36]:
a[0,0]

0.6964691855978616

In [37]:
a[0,-1]

0.2268514535642031

In [38]:
a[0:2]

array([[0.69646919, 0.28613933, 0.22685145],
       [0.55131477, 0.71946897, 0.42310646]])

In [39]:
a[0,1:3]

array([0.28613933, 0.22685145])

#### Modifying a slice will modify the array

In [40]:
a[0,0]

0.6964691855978616

In [41]:
a[0,0] = 10

In [42]:
a

array([[10.        ,  0.28613933,  0.22685145],
       [ 0.55131477,  0.71946897,  0.42310646],
       [ 0.9807642 ,  0.68482974,  0.4809319 ],
       [ 0.39211752,  0.34317802,  0.72904971],
       [ 0.43857224,  0.0596779 ,  0.39804426],
       [ 0.73799541,  0.18249173,  0.17545176]])

#### Boolean indexing

In [43]:
bool_idx = (a > 0.7)
bool_idx

array([[ True, False, False],
       [False,  True, False],
       [ True, False, False],
       [False, False,  True],
       [False, False, False],
       [ True, False, False]])

In [44]:
print(a[bool_idx])
print(a[a > 0.7]) # in a single expression

[10.          0.71946897  0.9807642   0.72904971  0.73799541]
[10.          0.71946897  0.9807642   0.72904971  0.73799541]


#### Reshaping arrays

In [45]:
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
grid = np.arange(1, 7).reshape((2, 3))
print(grid)

[[1 2 3]
 [4 5 6]]


#### Subarrays return views, not copies!

In [47]:
a

array([[10.        ,  0.28613933,  0.22685145],
       [ 0.55131477,  0.71946897,  0.42310646],
       [ 0.9807642 ,  0.68482974,  0.4809319 ],
       [ 0.39211752,  0.34317802,  0.72904971],
       [ 0.43857224,  0.0596779 ,  0.39804426],
       [ 0.73799541,  0.18249173,  0.17545176]])

In [ ]:
# we take a slice of array "a" and store it in a new variable "a_chunk"
a_chunk = a[1:3, 0:2]
a_chunk

In [ ]:
# modifying "a_chung" also modifies "a"
a_chunk[0,0] = 0
print(a_chunk)
print("\n")
print(a)

#### Creating copies

In [ ]:
a_copy = a.copy()

In [ ]:
# modifying a copy does not modify the original
a_copy[0,0] = 0
print(a_copy, "\n")
print(a)

#### 3-D arrays

In [ ]:
b = np.random.random((5,2,3))
print(b)

### 4-D arrays

In [ ]:
c = np.random.random((2,3,4,5))
print(c)


### Operations:

- np.sum, np.multiply, np.power...

- np.mean, np.std...

In [ ]:
x = np.array([1,2,3])
y = np.array([4,5,6])
x **y  # works with *, /, **  element wise 

Lists do not behave the same way: sum means concatenation

In [ ]:
[1,2,3] + [4,5,6]

In [ ]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])
print("x", "\n", x)
print("y", "\n", y)

In [ ]:
print (x + y)

In [ ]:
# Mean of each column in matrix a
print(np.mean(a, axis=0))
  
# Mean of each row in matrix a
print(np.mean(a, axis=1))

# Mean of all the elements in the first two groups of array b
np.mean(b[:2])

In [ ]:
# compute the standard deviation of this array, first using np.std() and then without using this function
np.random.seed(123)
rand = np.random.random(10)
rand

In [ ]:
squared_deviations = (rand - np.mean(rand))**2
squared_deviations

In [ ]:
np.sqrt(squared_deviations.mean())

#### Multiplying bones broken & favourite numbers

In [ ]:
# we use np.Nan for the missing data
bones_broken = np.array([0,3,0,1,0,1,0,4,3,2,2,0,0,2,2,4,0,np.NaN,0,0,1,0,np.NaN,1,0,0,0])
bones_broken

In [ ]:
# we will replace missing data with the rounded mean
nan_replacement = round(np.nanmean(bones_broken))

In [ ]:
bones_broken = np.nan_to_num(bones_broken, nan=nan_replacement)
bones_broken

In [ ]:
fav_num = np.array([7,4,24,6,8,7,7,13,3,5,13,0,np.NaN,14,7,7,7,np.NaN,23,9,4,24,19,8,10,0,8])

In [ ]:
# we will replace missing data with the mode

from scipy.stats import mode # numpy doesn't have mode, we import it from scipy
most_freq_fav_num = mode(fav_num)
print(most_freq_fav_num) # this fives both the mode and its freq count
print(most_freq_fav_num[0]) # we just need the actual mode

In [ ]:
fav_num = np.nan_to_num(fav_num, nan=most_freq_fav_num[0])
fav_num

In [ ]:
# now we can multiply both arrays
bones_broken * fav_num

#### Performance of numpy operations vs lists

In [ ]:
from time import time

n = 1000000

start_time = time()

big_slow_list = []

for i in range(1, n):
    big_slow_list.append(i**3)

end_time = time()
    
print(end_time - start_time)

In [ ]:
n = 1000000

start_time = time()

big_fast_array = np.arange(1,n)**3

end_time = time()
    
print(end_time - start_time)

#### Concatenate

In [ ]:
first = np.array([[1,2,3],[4,5,6]])
second = np.array([[0,0,0], [9,9,9]])

In [ ]:
first

In [ ]:
second

In [ ]:
np.concatenate([first, second])

In [ ]:
np.concatenate([first, second], axis=1)

In [ ]:
one_dim = np.array([1,1,1])

In [ ]:
np.vstack([first, one_dim])

### Transpose

In [ ]:
print(first)

In [ ]:
print(first.T)

#### Splitting arrays

In [ ]:
hundred = np.array(range(1,101))

In [ ]:
hundred

In [ ]:
first_half, second_half = np.split(hundred, [50])

In [ ]:
first_half

In [ ]:
second_half