# Lambda function

In [2]:
x = lambda a : a + 10

print(x(5))

15


In [3]:
x = lambda a, b : a * b
print(x(6, 7))

42


In [4]:
def myfunc(n):
  return lambda a : a * n

mydoubler = myfunc(2)

mydoubler(13)

26

## Numpy code along


In [5]:
# 'np' is the conventional alias for numpy
import numpy as np

#### Numpy arrays

In [6]:
## one dimensional array is a vector
a = np.array([5,3,2])

In [8]:
a.shape

(3,)

#### Generate an array with random numbers

In [22]:
np.random.seed(1001)
a = np.random.random((6,2))
a

array([[0.30623218, 0.26506357],
       [0.19606006, 0.43052148],
       [0.02311355, 0.19578192],
       [0.35280529, 0.22324202],
       [0.61352186, 0.58045711],
       [0.85356768, 0.04113054]])

### Other ways to create arrays

#### List to array

This works the same way whether you have a list of lists, a list of tuples, a tuple of lists, or a tuple of tuples.

In [29]:
lst_lst = [[[1,2,3],[4,5,6],[7,8,9]]]
d = np.array(lst_lst)
print(d.shape)

(1, 3, 3)


#### Constant arrays

In [30]:
a = np.zeros((2,2))  # Create an array of all zeros
print(a, "\n")

b = np.ones((3,2))   # Create an array of all ones
print(b, "\n")

c = np.full((2,2), 7) # Create a constant array
print(c)

[[0. 0.]
 [0. 0.]] 

[[1. 1.]
 [1. 1.]
 [1. 1.]] 

[[7 7]
 [7 7]]


#### Sequential arrays

In [31]:
# Create an array filled with a linear sequence
# Starting at 0, ending at 20, stepping by 2
# (this is similar to the built-in range() function)
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [32]:
# Create an array of five values evenly spaced between 0 and 1
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [33]:
# Create a 3x3 array of normally distributed random values
# with mean 0 and standard deviation 1
np.random.normal(0, 1, (3, 3))

array([[ 0.82911495, -0.02329881, -0.20856395],
       [-0.91661975, -1.07474258, -0.08614349],
       [ 1.17583854, -1.63509173,  1.228194  ]])

In [34]:
# Create a 3x3 array of random integers in the interval [0, 10)
np.random.randint(0, 10, (3, 3))

array([[2, 2, 3],
       [2, 8, 6],
       [0, 1, 5]])

#### Array Attributes

In [35]:
np.random.seed(123)
a = np.random.random((6,3))
a

array([[0.69646919, 0.28613933, 0.22685145],
       [0.55131477, 0.71946897, 0.42310646],
       [0.9807642 , 0.68482974, 0.4809319 ],
       [0.39211752, 0.34317802, 0.72904971],
       [0.43857224, 0.0596779 , 0.39804426],
       [0.73799541, 0.18249173, 0.17545176]])

In [36]:
a.shape

(6, 3)

In [37]:
a.size

18

In [38]:
a.ndim

2

In [39]:
a.dtype

dtype('float64')

In [40]:
b = np.array([1,3,4])

In [41]:
b.dtype

dtype('int32')

In [42]:
b.itemsize

4

In [43]:
c = np.array([1,3,4], dtype="int8") # smaller integers

In [44]:
c.itemsize

1

In [46]:
c = np.array([1,3,4]).astype(np.int8)

In [47]:
c

array([1, 3, 4], dtype=int8)

In [52]:
new_array = np.array([1,2,True])

In [53]:
new_array

array([1, 2, 1])

In [56]:
(new_array).dtype

dtype('int32')

#### Array indexing

In [57]:
a

array([[0.69646919, 0.28613933, 0.22685145],
       [0.55131477, 0.71946897, 0.42310646],
       [0.9807642 , 0.68482974, 0.4809319 ],
       [0.39211752, 0.34317802, 0.72904971],
       [0.43857224, 0.0596779 , 0.39804426],
       [0.73799541, 0.18249173, 0.17545176]])

In [58]:
a[0]

array([0.69646919, 0.28613933, 0.22685145])

In [59]:
a[0,0]

0.6964691855978616

In [60]:
a[0,-1]

0.2268514535642031

In [61]:
a[0:2]

array([[0.69646919, 0.28613933, 0.22685145],
       [0.55131477, 0.71946897, 0.42310646]])

In [62]:
a[0,1:3]

array([0.28613933, 0.22685145])

#### Modifying a slice will modify the array

In [63]:
a[0,0]

0.6964691855978616

In [64]:
a[0,0] = 10

In [65]:
a

array([[10.        ,  0.28613933,  0.22685145],
       [ 0.55131477,  0.71946897,  0.42310646],
       [ 0.9807642 ,  0.68482974,  0.4809319 ],
       [ 0.39211752,  0.34317802,  0.72904971],
       [ 0.43857224,  0.0596779 ,  0.39804426],
       [ 0.73799541,  0.18249173,  0.17545176]])

#### Boolean indexing

In [66]:
print(a)

[[10.          0.28613933  0.22685145]
 [ 0.55131477  0.71946897  0.42310646]
 [ 0.9807642   0.68482974  0.4809319 ]
 [ 0.39211752  0.34317802  0.72904971]
 [ 0.43857224  0.0596779   0.39804426]
 [ 0.73799541  0.18249173  0.17545176]]


In [67]:
bool_idx = (a > 0.7)
bool_idx

array([[ True, False, False],
       [False,  True, False],
       [ True, False, False],
       [False, False,  True],
       [False, False, False],
       [ True, False, False]])

In [69]:
#print(a[bool_idx])
print(a[a > 0.7]) # in a single expression

[10.          0.71946897  0.9807642   0.72904971  0.73799541]


#### Reshaping arrays

In [70]:
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [71]:
np.arange(1,7)

array([1, 2, 3, 4, 5, 6])

In [74]:
grid = np.arange(1, 9).reshape((3, 3))
print(grid)

ValueError: cannot reshape array of size 8 into shape (3,3)

#### Subarrays return views, not copies!

In [ ]:
a

In [ ]:
# we take a slice of array "a" and store it in a new variable "a_chunk"
a_chunk = a[1:3, 0:2]
a_chunk

In [ ]:
# modifying "a_chung" also modifies "a"
a_chunk[0,0] = 0
print(a_chunk)
print("\n")
print(a)

#### Creating copies

In [ ]:
a_copy = a.copy()

In [ ]:
# modifying a copy does not modify the original
a_copy[0,0] = 0
print(a_copy, "\n")
print(a)

#### 3-D arrays

In [ ]:
b = np.random.random((5,2,3))
print(b)

### 4-D arrays

In [ ]:
c = np.random.random((2,3,4,5))
print(c)


### Operations:

- np.sum, np.multiply, np.power...

- np.mean, np.std...

In [ ]:
x = np.array([1,2,3])
y = np.array([4,5,6])
x **y  # works with *, /, **  element wise 

Lists do not behave the same way: sum means concatenation

In [75]:
[1,2,3] + [4,5,6]

[1, 2, 3, 4, 5, 6]

In [76]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])
print("x", "\n", x)
print("y", "\n", y)

x 
 [[1 2]
 [3 4]]
y 
 [[5 6]
 [7 8]]


In [77]:
print (x + y)

[[ 6  8]
 [10 12]]


In [ ]:
# Mean of each column in matrix a
print(np.mean(a, axis=0))
  
# Mean of each row in matrix a
print(np.mean(a, axis=1))

# Mean of all the elements in the first two groups of array b
np.mean(b[:2])

In [ ]:
# compute the standard deviation of this array, first using np.std() and then without using this function
np.random.seed(123)
rand = np.random.random(10)
rand

In [ ]:
squared_deviations = (rand - np.mean(rand))**2
squared_deviations

In [ ]:
np.sqrt(squared_deviations.mean())

In [85]:
new_array = np.array([[1,2],[3,4],[5,6]])

In [86]:
new_array

array([[1, 2],
       [3, 4],
       [5, 6]])

In [87]:
new_array.T

array([[1, 3, 5],
       [2, 4, 6]])

In [109]:
random_list = [1,2,3,'hi','',[], {}, None]

In [110]:
comp_list = []
for i in random_list:
    comp_list.append(i)

In [111]:
comp_list = [i for i in random_list if i]

In [112]:
comp_list

[1, 2, 3, 'hi']

In [133]:
random_list = '012345helloparrot'
random_list.find('hi')

-1

In [125]:
random_list = [0,1,2,3,'hi',5,6,7,8,9,10]

new_list = [i for i in random_list if random_list.index(i) %2==0 ]

In [126]:
new_list

[0, 2, 'hi', 6, 8, 10]

In [134]:
newnew_list = [1,2,3,4,5,6]
mydict = dict(zip(new_list,newnew_list))

In [135]:
range(mydict)

TypeError: 'dict' object cannot be interpreted as an integer

#### Multiplying bones broken & favourite numbers

In [ ]:
# we use np.Nan for the missing data
bones_broken = np.array([0,3,0,1,0,1,0,4,3,2,2,0,0,2,2,4,0,np.NaN,0,0,1,0,np.NaN,1,0,0,0])
bones_broken

In [ ]:
# we will replace missing data with the rounded mean
nan_replacement = round(np.nanmean(bones_broken))

In [ ]:
bones_broken = np.nan_to_num(bones_broken, nan=nan_replacement)
bones_broken

In [ ]:
fav_num = np.array([7,4,24,6,8,7,7,13,3,5,13,0,np.NaN,14,7,7,7,np.NaN,23,9,4,24,19,8,10,0,8])

In [ ]:
# we will replace missing data with the mode

from scipy.stats import mode # numpy doesn't have mode, we import it from scipy
most_freq_fav_num = mode(fav_num)
print(most_freq_fav_num) # this fives both the mode and its freq count
print(most_freq_fav_num[0]) # we just need the actual mode

In [ ]:
fav_num = np.nan_to_num(fav_num, nan=most_freq_fav_num[0])
fav_num

In [ ]:
# now we can multiply both arrays
bones_broken * fav_num

#### Performance of numpy operations vs lists

In [78]:
from time import time

n = 1000000

start_time = time()

big_slow_list = []

for i in range(1, n):
    big_slow_list.append(i**3)

end_time = time()
    
print(end_time - start_time)

1.3422753810882568


In [79]:
n = 1000000

start_time = time()

big_fast_array = np.arange(1,n)**3

end_time = time()
    
print(end_time - start_time)

0.01199793815612793


#### Concatenate

In [ ]:
first = np.array([[1,2,3],[4,5,6]])
second = np.array([[0,0,0], [9,9,9]])

In [ ]:
first

In [ ]:
second

In [ ]:
np.concatenate([first, second])

In [ ]:
np.concatenate([first, second], axis=1)

In [ ]:
one_dim = np.array([1,1,1])

In [ ]:
np.vstack([first, one_dim])

### Transpose

In [ ]:
print(first)

In [ ]:
print(first.T)

#### Splitting arrays

In [ ]:
hundred = np.array(range(1,101))

In [ ]:
hundred

In [ ]:
first_half, second_half = np.split(hundred, [50])

In [ ]:
first_half

In [ ]:
second_half